version: "3"
services:
  nginx:
    build:
      context: ./www
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./www/design/dist:/usr/share/nginx/html
    restart: unless-stopped
