version: "3"

networks:
  traefik-proxy:
    external: true

services:
  nginx:
    build:
      context: ./www
      dockerfile: ./Dockerfile
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.<service>-rtr.rule=Host(`www.$DOMAINNAME`)
      - traefik.http.routers.<service>-rtr.tls=true
      - traefik.http.routers.<service>-rtr.tls.certresolver=letsencrypt
      ## Middlewares Rules
    restart: unless-stopped
    networks:
      - traefik-proxy
