version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./live:/usr/share/nginx/html
    restart: unless-stopped
