version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./live:/usr/share/nginx/html
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=url.emith.dev
      - LETSENCRYPT_HOST=url.emith.dev
      - LETSENCRYPT_EMAIL=webmaster@emith.dev
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
